variables:
  CI_DOCKERHUB_IMAGE: huncrys/tvhproxy

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/kaniko-build@~latest
    inputs:
      licenses: BSD-3-Clause
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/manifest-tool-manifest@~latest
